"""awwall: egress allowlist that fails closed."""

import re
from typing import NamedTuple, Optional


class AllowRule(NamedTuple):
    pattern: str
    rule_type: str
    description: str = ""

class Policy:
    def __init__(self, rules: Optional[list] = None):
        self.rules = rules or []

    @classmethod
    def from_dict(cls, data):
        if not isinstance(data, dict):
            raise ValueError("Policy must be a dictionary")
        rules_data = data.get("rules", [])
        if not isinstance(rules_data, list):
            raise ValueError("rules must be a list")
        rules = []
        for rule_dict in rules_data:
            if not isinstance(rule_dict, dict):
                raise ValueError("Each rule must be a dictionary")
            pattern = rule_dict.get("pattern")
            rule_type = rule_dict.get("rule_type")
            description = rule_dict.get("description", "")
            if not pattern or not rule_type:
                raise ValueError("Each rule must have pattern and rule_type")
            if rule_type not in ("exact", "domain", "glob"):
                raise ValueError(f"Invalid rule_type: {rule_type}")
            rules.append(AllowRule(pattern, rule_type, description))
        return cls(rules)

    def check(self, host):
        host = host.strip().lower()
        for rule in self.rules:
            if self._rule_matches(host, rule):
                return True, rule
        return False, None

    def _rule_matches(self, host, rule):
        pattern = rule.pattern.lower()
        if rule.rule_type == "exact":
            return host == pattern
        elif rule.rule_type == "domain":
            if host == pattern:
                return True
            if host.endswith("." + pattern):
                return True
            return False
        elif rule.rule_type == "glob":
            regex = re.escape(pattern).replace(r"\*", ".*")
            return bool(re.fullmatch(regex, host))
        return False

    def to_dict(self):
        return {
            "rules": [
                {
                    "pattern": rule.pattern,
                    "rule_type": rule.rule_type,
                    "description": rule.description
                }
                for rule in self.rules
            ]
        }

    def to_hosts_format(self):
        lines = [
            "# Generated by awwall - egress allowlist",
            "# NOTE: This only represents the rules in awwall format.",
            "# Use 'awwall emit --format iptables' for actual firewall rules.",
        ]

        for rule in self.rules:
            if rule.rule_type in ("exact", "domain"):
                comment = f" # {rule.description}" if rule.description else ""
                lines.append(f"127.0.0.1 {rule.pattern}{comment}")

        return "\n".join(lines) + "\n"

    def to_iptables_format(self):
        lines = [
            "#!/bin/bash",
            "# Generated by awwall - egress allowlist",
            "# NOTE: These rules require integration with DNS resolution.",
            "# Recommended: use this with conntrack + DNS interception.",
            "",
            "# Default: DROP outbound",
            "iptables -P OUTPUT DROP",
            "iptables -P FORWARD DROP",
            "",
            "# Allow localhost",
            "iptables -A OUTPUT -d 127.0.0.1 -j ACCEPT",
            "iptables -A OUTPUT -d ::1 -j ACCEPT",
            "",
            "# Allow related/established",
            "iptables -A OUTPUT -m state --state ESTABLISHED,RELATED -j ACCEPT",
            "",
            "# Rules (requires DNS A/AAAA record resolution)",
        ]

        for rule in self.rules:
            comment = f" # {rule.description}" if rule.description else ""
            if rule.rule_type == "exact":
                lines.append(f"# EXACT: {rule.pattern}{comment}")
                lines.append(f"# iptables -A OUTPUT -d <IP-of-{rule.pattern}> -j ACCEPT")
            elif rule.rule_type == "domain":
                lines.append(f"# DOMAIN: {rule.pattern}{comment}")
                lines.append(f"# iptables -A OUTPUT -d <IP-of-*.{rule.pattern}> -j ACCEPT")
            elif rule.rule_type == "glob":
                lines.append(f"# GLOB: {rule.pattern}{comment}")
                lines.append(f"# iptables -A OUTPUT -d <IP-matching-{rule.pattern}> -j ACCEPT")

        return "\n".join(lines) + "\n"

__all__ = ["Policy", "AllowRule"]

